import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Each top-level folder under docs/ is one section with its own sidebar.
// Sub-folders become categories; configure them with `_category_.json`.
const sidebars: SidebarsConfig = {
  research: [{type: 'autogenerated', dirName: 'research'}],
  learning: [{type: 'autogenerated', dirName: 'learning'}],
};

export default sidebars;
